#!/usr/bin/perl
#####################################################
#
# PROGRAM       : bluearc-metrics
# USE           : get bluearc metrics via SNMP and output them 
# AUTHOR        : James Braid
# DATE          : 20091027
#
# NOTES         : 1. very basic
#               : 2. metrics seem to all be indexed by pnode
#
#####################################################

use strict;
use warnings;
use SNMP;
use Data::Dumper;
use Getopt::Long qw(:config permute bundling);
use List::Util qw(first);
use FindBin;

my $mib = $FindBin::Bin . '/cpqwcrm.mib';
my $mib2 = $FindBin::Bin . '/cpqhost.mib';
my $OPT = {};

GetOptions($OPT,
    'help|h'        => \&info,
    'hostname=s',
    'temperature|t',
    'fan|f',
    'debug',
) or die "options parsing failed: $!";

my $mcs_host = $OPT->{hostname} || die "no hostname specified";
$mcs_host =~ s/\..*//g;
my $snmp = new SNMP::Session(DestHost => $mcs_host, Version => 1);
die "failed to connect" unless $snmp;

&SNMP::addMibFiles($mib2);
&SNMP::addMibFiles($mib);
#$SNMP::debugging = 1;

# get sensors
my $sensor_table = $snmp->gettable('cpqWcrmWaterCoolUnitSensorTable');

if ($OPT->{temperature}) {
    my @want;
    my %out_table;
    my %in_table;
    #print Dumper $sensor_table;

    # get temperature sensors
    @want = grep { $sensor_table->{$_}->{waterCoolUnitSensorText} =~ /(Temp. \d+ (Out|In)|/ } (keys %$sensor_table);

    foreach (sort @want) {
        print $sensor_table->{$_}->{waterCoolUnitSensorText} . ":" . $sensor_table->{$_}->{waterCoolUnitSensorValue} . " ";
    }
}

if ($OPT->{fan}) {
    my @want;
    # get output sensors
    @want = grep { $sensor_table->{$_}->{waterCoolUnitSensorText} =~ /Fan/ } (keys %$sensor_table);

    foreach (sort @want) {
        print $sensor_table->{$_}->{waterCoolUnitSensorText} . ":" . $sensor_table->{$_}->{waterCoolUnitSensorValue} . " ";
    }

}


print "\n";

sub info {
    print <<END;

 $0 - HP MCS statistics for cacti

 --hostname         - hostname of server to connect to
 -t --temperature   - temperature stats

END

    exit 1;
}
